# Site settings
title: _espi_
email: espi@espipinxo.com
description: >
  Jordi Espinosa Castells (known how _espi_). geek, runner, tester, cooker, and daddy...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.espipinxo.com" # the base hostname & protocol for your site
timezone: Europe/Madrid

permalink: /:year/:month/:day/:title/

twitter_username: jespinosa
github_username:  jespicas
google-tracking-id: "UA-73234844-1"
disqus-shortname: "espi"

# Build settings
highlighter: pygments
markdown: kramdown

pages_list:
  'Blog': 'blog'
  'About...': 'about'
  'Contact': 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

# Career variables

events:
  - image: "/assets/career/sundiopartofteam.jpg"
    date: "2012-Today"
    description: "Sundio Group QA Team"
  - image: "/assets/career/android.png"
    date: "Today"
    description: "Learning Android and develop little App"
  - image: "/assets/career/kodi.png"
    date: "Today"
    description: "Develop Kodi addon"
  - image: "/assets/career/tux.png"
    date: "Today"
    description: "non stop learn"
  - image: "/assets/career/ccpe_logotip.jpg"
    date: "2009-2012"
    description: "Service Desk on Consell Comarcal del Pla de l'Estany again"
  - image: "/assets/career/sunweb.png"
    date: "2005-2008"
    description: "Sunweb Vakanties Develop Core and Website  . <strong>vb.net</strong>"
  - image: "/assets/career/ccpe_logotip.jpg"
    date: "2003-2005"
    description: "Service Desk on Consell Comarcal del Pla de l'Estany"
  - image: "/assets/career/megatro.jpg"
    date: "1995-2003"
    description: "Megatro C.B."

# First image of the Career timeline
career-img: "/img/mecareer.jpg"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "twitter"
    url: "https://twitter.com/jespinosa"
  - title: "github"
    url: "https://github.com/jespicas"
  - title: "linkedin"
    url: "https://es.linkedin.com/in/jordi-espinosa-2b059329"

404-img: "/img/labtocat.png"
favicon: "/img/favicon.ico"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "README.md", "CNAME", "Gemfile", "Gemfile.md", "vendor"]

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-paginate

sass:
    sass_dir: _sass
